# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6abdcd1a412abfa9893006ae3d682684b9979301f56630bae74c2d78693060878405b3f9a24689f02bc58ba1804555bea39dfd4bd8b8996f60bb5243c7425c8

test:
  secret_key_base: 1bf46467d04dae4a827f3079b3f2bfd1a9fc8b39bc06233cefd5b63ee46226c58dc3143509c3160f074ed97c04cb23f7c566b93b5fea30b1333a89878be9b10c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
